### PR TITLE
Add load/save preset REST api

### PR DESCRIPTION
**Pull request by anoyetta**
Added REST API method.

```
# Load preset by name
GET /preset/{name}/load
```
```
# Save current waymarks to preset
POST /preset/{name}/save
```

### CODE REVIEW

**Comment by LeonBlade** [comment]
Thank you for your submission.

**Comment by LeonBlade** [comment]
@anoyetta I should have done testing before pushing this live, but this feature does not work as intended for me.  Were you able to get it working properly?  There are some problems.

**Comment by anoyetta** [comment]
yes, I tested.
I forgot to write the HTTP method.
"load" is GET
"save" is POST

**Comment by LeonBlade** [comment]
I'm getting an exception error when saving presets because the subscription isn't on the proper thread to modify the preset array.  I haven't looked into load yet, but I know it errors as well.

**Comment by LeonBlade** [comment]
I had to use the dispatcher to fix the save endpoint.  The load endpoint worked fine, but not with Triggernometry because it only does POST requests, so I just made a POST version as well.  Thank you again for your contribution! 🙇‍♂️

**Pull request merged**
